### PR TITLE
ignore l2 keystones notifications in tests

### LINKED ISSUE #110: fragile test
### Confirmation

- [X] I have checked for similar issues.

### Describe the bug

There seems to be a fragile test error during cleanup, this is the test failing https://github.com/hemilabs/heminetwork/actions/runs/9016650152/job/24773648158?pr=109

I believe this is the error, I think that the database is being closed before its consumers
```
2024-05-09 11:36:19 ERROR bfg bfg.go:215 Failed to handle handle l2 keystones request request [::1]:40150: error getting l2 keystones: sql: database is closed [1715254579:651ddc8d25b44529]
2024-05-09 11:36:19 ERROR bfg bfg.go:225 Failed to handle handle l2 keystones request request: protocol write failed: failed to write JSON message: failed to marshal JSON: failed to write msg: failed to acquire lock: context canceled
--- FAIL: TestL2Keystone (1.22s)
    e2e_ext_test.go:785: Creating test database e2e_ext_test_db__4536514
    e2e_ext_test.go:785: Applying SQL file 0001.sql
    e2e_ext_test.go:785: Applying SQL file 0002.sql
    e2e_ext_test.go:785: Applying SQL file 0003.sql
    e2e_ext_test.go:785: Applying SQL file 0004.sql
    e2e_ext_test.go:785: Applying SQL file 0005.sql
    e2e_ext_test.go:785: Applying SQL file 0006.sql
    e2e_ext_test.go:785: Database version: 6
    e2e_ext_test.go:115: connecting to http://localhost:43809/v1/ws/private
    e2e_ext_test.go:115: connecting to http://localhost:39901/v1/ws/public
    e2e_ext_test.go:864: unexpected command bfgapi-l2-keystones-notification
    e2e_ext_test.go:222: Removing test database e2e_ext_test_db__4536514
```

### Expected behaviour

test should not be fragile

### Environment

Version: 
Operating System: 
Architecture: 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ClaytonNorthey92**
**Summary**
when we broadcast notifications for new l2 keystones, there is no guarantee when those broadcasts will be sent out since it is async.  we had a test that would create new keystones, then write an api rpc request, then wait for a response.  occasionally, the response would be the notifications for new l2 keystones that were created earlier in the tests.  

**Changes**
we can safely ignore those in this test.

fixes #110

### CODE REVIEW

File: e2e/e2e_ext_test.go [hunk 1]
```diff
@@ -855,13 +855,26 @@ func TestL2Keystone(t *testing.T) {
...
+		// call above, if they haven't been broadcast yet.  ignore those.
+		if command == bfgapi.CmdL2KeystonesNotification {
+			continue
+		}
+
+		if command == bfgapi.CmdL2KeystonesResponse {
+			break
+		} else {
+			t.Fatalf("unexpected command %s", command)
+		}
```
Comment (joshuasing) [inline e2e/e2e_ext_test.go:877]: I think we could simplify this to the following, what do you think?
```suggestion
		if command != bfgapi.CmdL2KeystonesResponse {
			t.Fatalf("unexpected command %s", command)
		}

		break
```

Comment (ClaytonNorthey92) [reply e2e/e2e_ext_test.go:877]: yup that works

**Review by joshuasing — APPROVED** [review]

**Review by max-sanchez — APPROVED** [review]
