### PR TITLE
retry mine keystone on failure

### LINKED ISSUE #7: Implement "retry" when mining L2 Keystones in PoP Miner
### Confirmation

- [X] I have checked for similar issues.

### Problem

As of right now, if pop miner fails to mine a keystone, it won't retry.  It's possible a one-off error occurs in this moment and a retry would succeed.

### Suggested solution

Implement some sort of retry for pop miner when "mining keystones".  This will require some discussion; the retry strategy, limit, etc. all need to be discussed.

### Additional Information

as of writing this, this refers to the `mineKeystone` function in `popm.go`

### PR DESCRIPTION
**Pull request by ClaytonNorthey92**
**Summary**
We need a way to retry mining keystones if they fail, this provides a solution.

Fixes #7 

**Changes**
* keep buffer of 10 newest keystones known
* upon receiving a keystone, only insert into buffer if it is newer than the oldest keystone
* if buffer is full, drop oldest keystone upon inserting another
* when a keystone is mined, mark it as "processed" to not repeat mining same keystone
* generate fewer btc blocks in full network e2e test, since we have a retry strategy now 
* remove retry from full network e2e test

### CODE REVIEW

File: service/popm/popm.go [hunk 1]
```diff
@@ -50,6 +50,108 @@ func init() {
...
+	mtx     sync.Mutex
+	mapping map[string]*L2KeystonePriorityBufferElement
+	size    int
+}
+
+// L2KeystonePriorityBufferElement holds an L2Keystone and whether it has been
+// "processed" or not
+type L2KeystonePriorityBufferElement struct {
+	l2Keystone         hemi.L2Keystone
+	requiresProcessing bool
```
Comment (ClaytonNorthey92) [inline service/popm/popm.go:66]: hmm we might want to add a "currentlyProcessing" flag here as well; since this can be triggered by both timer and new keystone

File: service/popm/popm.go [hunk 2]
```diff
@@ -50,6 +50,112 @@ func init() {
...
+func (r *L2KeystonePriorityBuffer) ForEach(cb func(ks hemi.L2Keystone) error) {
+	r.mtx.Lock()
+	copies := []hemi.L2Keystone{}
+	for _, v := range r.mapping {
+		if v.requiresProcessing {
+			copies = append(copies, v.l2Keystone)
+
+			// temporarily set this to false, so another goroutine doesn't
+			// try to process
+			v.requiresProcessing = false
```
Comment (marcopeereboom) [inline service/popm/popm.go:134]: This looks racy. You could have started traversing the map while the variable is not set yet. This is a logic race. Setting and unsetting the variable should really happen in the same lock.

File: service/popm/popm.go [hunk 3]
```diff
@@ -50,6 +50,112 @@ func init() {
...
+	slices.SortFunc(copies, func(a, b hemi.L2Keystone) int {
+		return int(b.L2BlockNumber) - int(a.L2BlockNumber)
+	})
+
+	for _, e := range copies {
+		mined := hemi.L2KeystoneAbbreviate(e).Serialize()
+		key := hex.EncodeToString(mined[:])
+
+		err := cb(e)
+		r.mtx.Lock()
```
Comment (marcopeereboom) [inline service/popm/popm.go:149]: I didn't want to say this but this is probably where you want to serialize using a channel. I may be missing some subtlety so don't take this as gospel truth but once you start seeing locking/unlocking in the same loop it typically means the code should be rethought to prevent that from happening.

File: service/popm/popm_test.go [hunk 4]
```diff
@@ -12,6 +12,7 @@ import (
 	"fmt"
```
Comment (marcopeereboom) [inline service/popm/popm_test.go:12]: While I cannot put my finger on it, it seems not unlikely that there is a logic race/error somewhere in this code. I would create a test that has hundreds of go routines attacking the pipeline and see what `test -race` comes up with.

**Review by marcopeereboom — CHANGES_REQUESTED** [review]

File: service/popm/popm.go [hunk 5]
```diff
@@ -110,10 +123,11 @@ func NewMiner(cfg *Config) (*Miner, error) {
 
 	m := &Miner{
 		cfg:            cfg,
-		keystoneCh:     make(chan *hemi.L2Keystone, 3),
 		bfgCmdCh:       make(chan bfgCmd, 10),
 		holdoffTimeout: 5 * time.Second,
 		requestTimeout: 5 * time.Second,
+		mineNowCh:      make(chan struct{}, 1),
+		l2Keystones:    make(map[string]L2KeystoneProcessingContainer),
```
Comment (marcopeereboom) [inline service/popm/popm.go:130]: These really should have an initial size

File: service/popm/popm.go [hunk 6]
```diff
@@ -435,24 +449,50 @@ func (m *Miner) BitcoinUTXOs(ctx context.Context, scriptHash string) (*bfgapi.Bi
 	return ir, nil
 }
 
+func (m *Miner) mineKnownKeystones(ctx context.Context) {
+	keystonesFailed := false
+
+	m.ForEachL2Keystone(func(ks hemi.L2Keystone) error {
```
Comment (marcopeereboom) [inline service/popm/popm.go:455]: Why is this not a proper for loop?

**Review by marcopeereboom — CHANGES_REQUESTED** [review]
I may not be fully appreciating what is going on but let's spend a minute talking through this PR.

File: service/popm/popm.go (hunk 6 above)
Comment (ClaytonNorthey92) [reply service/popm/popm.go:455]: I wanted the `ForEachL2Keystone` to handle the locking and copying, I could pull it out and make it a for loop if you want

File: service/popm/popm.go (hunk 5 above)
Comment (ClaytonNorthey92) [reply service/popm/popm.go:130]: yeah I can do that, I can make it the size of the max keystones (10)

File: service/popm/popm.go [hunk 7]
```diff
@@ -785,3 +841,75 @@ func (m *Miner) Run(pctx context.Context) error {
...
+
+	m.l2Keystones[key] = toInsert
+}
+
+// l2KeystonesForProcessing creates copies of the l2 keystones, set them to
+// "processing", then returns the copies with the newest first
+func (m *Miner) l2KeystonesForProcessing() []hemi.L2Keystone {
+	m.mtx.Lock()
+
+	copies := []hemi.L2Keystone{}
```
Comment (marcopeereboom) [inline service/popm/popm.go:893]: This should be allocated with make outside of the mutex.

File: service/popm/popm.go (hunk 6 above)
Comment (ClaytonNorthey92) [reply service/popm/popm.go]: changed it to a `for` loop 👍

File: service/popm/popm.go (hunk 5 above)
Comment (ClaytonNorthey92) [reply service/popm/popm.go]: done 👍

File: service/popm/popm.go [hunk 8]
```diff
@@ -435,24 +449,66 @@ func (m *Miner) BitcoinUTXOs(ctx context.Context, scriptHash string) (*bfgapi.Bi
...
+	if !keystonesFailed {
+		return
+	}
+
+	// if a keystone failed, ensure that we retry
+	select {
+	case <-ctx.Done():
+		return
+	case <-time.After(l2KeystoneRetryTimeout):
+		go m.mineKnownKeystones(ctx)
```
Comment (marcopeereboom) [inline service/popm/popm.go:492]: you should not `go recurse calls. And can we get rid of the channel?

**Review by marcopeereboom — CHANGES_REQUESTED** [review]

File: service/popm/popm.go (hunk 7 above)
Comment (ClaytonNorthey92) [reply service/popm/popm.go:893]: sure 👍

File: service/popm/popm_test.go [hunk 9]
```diff
@@ -643,6 +981,136 @@ func TestConnectToBFGAndPerformMine(t *testing.T) {
...
+		case <-ctx.Done():
+			if ctx.Err() != nil {
+				t.Fatal(ctx.Err())
+			}
+		}
+		missing := false
+		for m := range messagesExpected {
+			message := fmt.Sprintf("%s", m)
+			if messagesReceived[message] != messagesExpected[m] {
+				t.Logf("still missing message %v, found %d want %d", m, messagesReceived[message], messagesExpected[m])
```
Comment (joshuasing) [inline service/popm/popm_test.go:1039]: Will this test pass if there are missing messages? :thinking:

File: service/popm/popm_test.go [hunk 10]
```diff
@@ -643,6 +981,136 @@ func TestConnectToBFGAndPerformMine(t *testing.T) {
...
+		case <-ctx.Done():
+			if ctx.Err() != nil {
+				t.Fatal(ctx.Err())
+			}
+		}
+		missing := false
+		for m := range messagesExpected {
+			message := fmt.Sprintf("%s", m)
+			if messagesReceived[message] < messagesExpected[m] {
+				t.Logf("still missing message %v, found %d want %d", m, messagesReceived[message], messagesExpected[m])
```
Comment (joshuasing) [inline service/popm/popm_test.go:1104]: Will this test pass if there are missing messages? :thinking:

File: service/popm/popm_test.go (hunk 9 above)
Comment (ClaytonNorthey92) [reply service/popm/popm_test.go:1039]: @joshuasing it won't pass, if there are missing messages it will time out because it won't break the `for` loop

File: service/popm/popm_test.go (hunk 10 above)
Comment (ClaytonNorthey92) [reply service/popm/popm_test.go:1104]: @joshuasing it won't pass, if there are missing messages it will time out because it won't break the `for` loop

File: service/popm/popm.go [hunk 11]
```diff
@@ -821,3 +864,76 @@ func (m *Miner) Run(pctx context.Context) error {
...
+
+// l2KeystonesForProcessing creates copies of the l2 keystones, set them to
+// "processing", then returns the copies with the newest first
+func (m *Miner) l2KeystonesForProcessing() []hemi.L2Keystone {
+	copies := make([]hemi.L2Keystone, 0)
+
+	m.mtx.Lock()
+
+	for i, v := range m.l2Keystones {
+
```
Comment (joshuasing) [inline service/popm/popm.go:919]: nit: I think this extra newline could be removed to help improve readability.

**Review by joshuasing — APPROVED** [review]

**Review by marcopeereboom — APPROVED** [review]
