### PR TITLE
bfgd, electrumx: make initial and max conns configurable

### LINKED ISSUE #205: bfgd, electrumx: make conn pool maximum size configurable
### Confirmation

- [X] I have checked for similar issues.

### Describe the bug

The current ElectrumX connection pool used by BFG keeps 5 connections open.
We are currently handling thousands of concurrent BFG connections, meaning keeping 5 connections with ElectrumX open is near useless.

### Expected behaviour

The maximum pool size should be made configurable through an environment variable and should have the default increased to a reasonable size.

### Environment

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by joshuasing**
**Summary**
Add environment variables to BFG for configuring the initial and maximum connections for the ElectrumX client's connection pool.

Resolves #205 

**Changes**
 - Add `initialConns` and `maxConns` params to `electrumx.NewClient`
 - Add `EXBTCInitialConns` and `EXBTCMaxConns` fields to BFG config
 - Add `BFG_EXBTC_INITIAL_CONNECTIONS` and `BFG_EXBTC_MAX_CONNS` to BFG
 - Sync environment variables in BFG Dockerfile

### CODE REVIEW

File: hemi/electrumx/electrumx.go [hunk 1]
```diff
@@ -129,13 +129,12 @@ const (
...
 
 // NewClient returns an initialised electrumx client.
-func NewClient(address string) (*Client, error) {
+func NewClient(address string, initialConns, maxConns int) (*Client, error) {
 	c := &Client{}
 
 	// The address may be empty during tests, ignore empty addresses.
 	if address != "" {
-		pool, err := newConnPool("tcp", address,
-			clientInitialConnections, clientMaximumConnections)
```
Comment (ClaytonNorthey92) [inline hemi/electrumx/electrumx.go:138]: can `clientInitialConnections` and `clientMaximumConnections` be removed completely?  or moved to the test file they are used in?

**Review by ClaytonNorthey92 — APPROVED** [review]
asking to remove/move some variables, not blocking

File: hemi/electrumx/electrumx.go (hunk 1 above)
Comment (joshuasing) [reply hemi/electrumx/electrumx.go:138]: They are currently still used in tests, although I can move them to the tests.

**Review by marcopeereboom — APPROVED** [review]
