### PR TITLE
remove lastErr variables from rpc_test.go

### LINKED ISSUE #182: tbc: fix unused 'lastErr' in RPC tests
### Confirmation

- [X] I have checked for similar issues.

### Describe the bug

Running `make staticcheck` results in `lastErr` variables being reported as unused:
```
service/tbc/rpc_test.go:72:4: this value of lastErr is never used (SA4006)
service/tbc/rpc_test.go:79:4: this value of lastErr is never used (SA4006)
service/tbc/rpc_test.go:89:4: this value of lastErr is never used (SA4006)
service/tbc/rpc_test.go:89:14: Errorf doesn't have side effects and its return value is ignored (SA4017)
(more omitted)
```

### Expected behaviour

Correct retry logic should be implemented in the TBC RPC tests.

### Environment

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ClaytonNorthey92**
**Summary**
lastErr was added to handle for something that likely shouldn't have been; it's an un-needed way to handle for errors.  replace with simply failing the test if there are errors.

**Changes**
remove lastErr variables from rpc_test.go

fixes #182

### CODE REVIEW

File: service/tbc/rpc_test.go [hunk 1]
```diff
@@ -56,42 +55,31 @@ func TestBlockHeadersByHeightRaw(t *testing.T) {
...
-			if err := json.Unmarshal(v.Payload, &response); err != nil {
-				t.Fatal(err)
-			}
-			break
-		} else {
-			lastErr = fmt.Errorf("received unexpected command: %s", v.Header.Command)
-		}
+	var v protocol.Message
+	err = wsjson.Read(ctx, c, &v)
+	if err != nil {
```
Comment (joshuasing) [inline service/tbc/rpc_test.go:73]: I think this err assignment could be nested (and in other functions below):
```suggestion
	if err = wsjson.Read(ctx, c, &v); err != nil {
```

File: service/tbc/rpc_test.go [hunk 2]
```diff
@@ -56,42 +55,31 @@ func TestBlockHeadersByHeightRaw(t *testing.T) {
...
 
-	if lastErr != nil {
-		t.Fatal(lastErr)
+	if v.Header.Command == tbcapi.CmdBlockHeadersByHeightRawResponse {
+		if err := json.Unmarshal(v.Payload, &response); err != nil {
+			t.Fatal(err)
+		}
+	} else {
+		t.Fatalf("received unexpected command: %s", v.Header.Command)
 	}
```
Comment (joshuasing) [inline service/tbc/rpc_test.go:83]: I think this logic can be inverted to fail early. (and in other functions below)
```suggestion
	if v.Header.Command != tbcapi.CmdBlockHeadersByHeightRawResponse {
		t.Fatalf("received unexpected command: %s", v.Header.Command)
	}

	if err := json.Unmarshal(v.Payload, &response); err != nil {
		t.Fatal(err)
	}
```

**Review by joshuasing — CHANGES_REQUESTED** [review]

File: service/tbc/rpc_test.go [hunk 3]
```diff
@@ -558,57 +492,49 @@ func TestBalanceByAddress(t *testing.T) {
...
+					t.Logf("unexpected diff: %s", diff)
 
-			if lastErr != nil {
-				t.Fatal(lastErr)
+					// there is a chance we just haven't finished indexing
+					// the blocks and txs, retry until timeout
+					continue
+				} else {
+					break
+				}
```
Comment (joshuasing) [inline service/tbc/rpc_test.go:537]: I think this `else` statement can be removed to simplify this logic.
```suggestion
				}

				break
```

**Review by joshuasing — APPROVED** [review]

File: service/tbc/rpc_test.go [hunk 4]
```diff
@@ -1692,11 +1510,11 @@ func indexAll(ctx context.Context, t *testing.T, tbcServer *Server) {
 
 	hash := bh.BlockHash()
 
-	if err := tbcServer.TxIndexer(ctx, &hash); err != nil {
+	if err = tbcServer.TxIndexer(ctx, &hash); err != nil {
 		t.Fatal(err)
 	}
 
-	if err := tbcServer.UtxoIndexer(ctx, &hash); err != nil {
+	if err = tbcServer.UtxoIndexer(ctx, &hash); err != nil {
```
Comment (marcopeereboom) [inline service/tbc/rpc_test.go:1517]: When using this idiom you really should keep `:=`.

**Review by marcopeereboom — CHANGES_REQUESTED** [review]

File: service/tbc/rpc_test.go (hunk 4 above)
Comment (joshuasing) [reply service/tbc/rpc_test.go:1517]: I think in most cases here, it is fine to set the value of `err` instead of shadowing it.

Comment (ClaytonNorthey92) [reply service/tbc/rpc_test.go:1517]: ah yes will fix

**Review by max-sanchez — APPROVED** [review]
